-- Dedicated multisoluciones_web database only. Additive and safe to re-run.
-- Deploy separately from the existing web form; never use the n8n internal DB.
DO $migration$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                 WHERE table_schema = 'public' AND table_name = 'contacts' AND column_name = 'locale') THEN
    ALTER TABLE public.contacts ADD COLUMN locale text NOT NULL DEFAULT 'en';
    UPDATE public.contacts c SET locale = COALESCE((
      SELECT r.locale FROM public.requests r WHERE r.contact_id = c.id
        AND r.locale IN ('en', 'es', 'ko', 'pt') ORDER BY r.id DESC LIMIT 1
    ), 'en');
  END IF;
END
$migration$;
ALTER TABLE public.messages ALTER COLUMN request_id DROP NOT NULL;
ALTER TABLE public.messages
  ADD COLUMN IF NOT EXISTS email_message_id text,
  ADD COLUMN IF NOT EXISTS email_in_reply_to text,
  ADD COLUMN IF NOT EXISTS email_references jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS email_subject text;

DO $migration$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'contacts_locale_check'
                 AND conrelid = 'public.contacts'::regclass) THEN
    ALTER TABLE public.contacts ADD CONSTRAINT contacts_locale_check
      CHECK (locale IN ('en', 'es', 'ko', 'pt'));
  END IF;
END
$migration$;

CREATE UNIQUE INDEX IF NOT EXISTS messages_email_message_id_uidx
  ON public.messages (email_message_id) WHERE email_message_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.contact_preference_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_id bigint NOT NULL REFERENCES public.contacts(id),
  request_id bigint REFERENCES public.requests(id),
  message_id bigint REFERENCES public.messages(id),
  source text NOT NULL CHECK (source IN ('web_form', 'email', 'admin')),
  preference text NOT NULL CHECK (preference IN ('email', 'call', 'whatsapp', 'none')),
  phone text,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  CHECK (preference NOT IN ('call', 'whatsapp') OR
         (phone IS NOT NULL AND phone ~ '^\+[1-9][0-9]{7,14}$'))
);
CREATE UNIQUE INDEX IF NOT EXISTS contact_preference_events_message_uidx
  ON public.contact_preference_events(message_id) WHERE message_id IS NOT NULL;

-- Claim before SMTP. A claimed record must NEVER be automatically re-queued:
-- a timeout/crash might mean SMTP accepted the message. Reconcile it manually.
CREATE TABLE IF NOT EXISTS public.email_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_id bigint NOT NULL REFERENCES public.contacts(id),
  request_id bigint REFERENCES public.requests(id),
  message_id bigint NOT NULL REFERENCES public.messages(id),
  kind text NOT NULL CHECK (kind IN ('admin', 'reply', 'telegram')),
  state text NOT NULL DEFAULT 'pending'
    CHECK (state IN ('pending', 'processing', 'sent', 'error', 'uncertain')),
  payload jsonb NOT NULL,
  claim_token text,
  claimed_at timestamptz,
  sent_at timestamptz,
  smtp_message_id text,
  error_message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(message_id, kind)
);
CREATE INDEX IF NOT EXISTS email_notifications_pending_idx
  ON public.email_notifications(id) WHERE state = 'pending';

-- $payload is the classifier result, passed as one bound JSON parameter.
-- The function is one transaction: dedup, history, preference, consent, outbox.
CREATE OR REPLACE FUNCTION public.persist_known_contact_email(p_payload jsonb)
RETURNS jsonb LANGUAGE plpgsql AS $function$
DECLARE
  v_email jsonb := COALESCE(p_payload->'email', '{}'::jsonb);
  v_contact public.contacts%ROWTYPE;
  v_message_id bigint;
  v_request_id bigint;
  v_suggested_request text := p_payload->>'requestId';
  v_refs jsonb;
  v_message_key text;
  v_preference text := p_payload->>'preference';
  v_phone text := NULLIF(btrim(p_payload->>'phone'), '');
  v_apply_preference boolean := false;
  v_reply boolean := false;
  v_admin boolean := false;
  v_telegram boolean := false;
  v_contact_data jsonb;
  v_notification_ids jsonb;
  v_correlated_requests bigint[];
  v_correlation text := p_payload->>'correlation';
BEGIN
  SELECT * INTO v_contact FROM public.contacts
  WHERE email_normalized = lower(btrim(COALESCE(v_email->>'fromEmail', v_email->>'from', '')))
  FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('status', 'ignored', 'reason', 'unknown_contact', 'send_reply', false, 'notify_admin', false);
  END IF;
  IF COALESCE(p_payload->>'action', 'ignore') = 'ignore'
     OR p_payload->>'saveMessage' IS DISTINCT FROM 'true' THEN
    RETURN jsonb_build_object('status', 'ignored', 'reason', COALESCE(p_payload->>'reason', 'classifier_ignore'),
                             'send_reply', false, 'notify_admin', false);
  END IF;
  v_message_key := NULLIF(btrim(v_email->>'messageId'), '');
  IF v_message_key IS NULL OR length(v_message_key) > 998 THEN
    RETURN jsonb_build_object('status', 'ignored', 'reason', 'invalid_message_id', 'send_reply', false, 'notify_admin', false);
  END IF;
  v_refs := CASE WHEN jsonb_typeof(v_email->'references') = 'array'
                 THEN v_email->'references' ELSE '[]'::jsonb END;
  SELECT array_agg(DISTINCT m.request_id) INTO v_correlated_requests
  FROM public.messages m JOIN public.requests r ON r.id = m.request_id
  WHERE m.contact_id = v_contact.id AND r.contact_id = v_contact.id
    AND m.direction = 'outbound' AND m.channel = 'email'
    AND m.email_message_id IS NOT NULL
    AND (v_refs ? m.email_message_id OR m.email_message_id = v_email->>'inReplyTo');
  IF cardinality(v_correlated_requests) > 1 THEN
    v_correlation := 'ambiguous';
  END IF;
  -- Do not assign an arbitrary/latest request. A classifier-selected request
  -- must belong to this contact and match stored outgoing SMTP metadata.
  IF v_correlation = 'matched' AND v_suggested_request ~ '^[0-9]+$'
     AND length(v_suggested_request) <= 18 THEN
    SELECT r.id INTO v_request_id FROM public.requests r
    WHERE r.id = v_suggested_request::bigint AND r.contact_id = v_contact.id
      AND EXISTS (
        SELECT 1 FROM public.messages m
        WHERE m.contact_id = v_contact.id AND m.request_id = r.id
          AND m.direction = 'outbound' AND m.channel = 'email'
          AND m.email_message_id IS NOT NULL
          AND (v_refs ? m.email_message_id OR m.email_message_id = v_email->>'inReplyTo')
      );
  END IF;
  INSERT INTO public.messages(contact_id, request_id, direction, channel, body, is_test,
                              email_message_id, email_in_reply_to, email_references, email_subject)
  VALUES(v_contact.id, v_request_id, 'inbound', 'email',
         COALESCE(v_email->>'body', v_email->>'text', ''), v_contact.is_test,
         v_message_key, NULLIF(v_email->>'inReplyTo', ''), v_refs, COALESCE(v_email->>'subject', ''))
  ON CONFLICT (email_message_id) WHERE email_message_id IS NOT NULL DO NOTHING
  RETURNING id INTO v_message_id;
  IF v_message_id IS NULL THEN
    RETURN jsonb_build_object('status', 'duplicate', 'send_reply', false, 'notify_admin', false);
  END IF;
  v_apply_preference := p_payload->>'action' = 'preference'
    AND v_correlation IN ('matched', 'unmatched', 'ambiguous')
    AND v_preference IN ('email', 'call', 'whatsapp', 'none')
    AND (v_preference NOT IN ('call', 'whatsapp') OR v_phone ~ '^\+[1-9][0-9]{7,14}$')
    AND (p_payload->>'correlation' <> 'matched' OR v_request_id IS NOT NULL);
  IF COALESCE(v_apply_preference, false) THEN
    UPDATE public.contacts SET contact_preference = v_preference,
      contact_phone = CASE WHEN v_preference IN ('call', 'whatsapp') THEN v_phone ELSE NULL END,
      contact_preference_updated_at = now(), updated_at = now()
    WHERE id = v_contact.id;
    INSERT INTO public.contact_preference_events(contact_id, request_id, message_id, source, preference, phone)
    VALUES(v_contact.id, v_request_id, v_message_id, 'email', v_preference,
           CASE WHEN v_preference IN ('call', 'whatsapp') THEN v_phone ELSE NULL END);
  END IF;
  v_admin := p_payload->>'notifyAdmin' = 'true';
  -- Preference confirmation is only sent if the DB accepted the update.
  v_reply := p_payload->>'sendReply' = 'true'
    AND (p_payload->>'action' <> 'preference' OR COALESCE(v_apply_preference, false));
  v_telegram := COALESCE(v_apply_preference, false) AND v_preference IN ('call', 'whatsapp');
  v_contact_data := jsonb_build_object('id', v_contact.id, 'name', v_contact.full_name,
    'full_name', v_contact.full_name, 'email', v_contact.email_normalized,
    'locale', v_contact.locale);
  INSERT INTO public.email_notifications(contact_id, request_id, message_id, kind, payload)
  SELECT v_contact.id, v_request_id, v_message_id, kind,
    p_payload || jsonb_build_object('contactId', v_contact.id, 'requestId', v_request_id,
                                    'messageId', v_message_id, 'contact', v_contact_data,
                                    'preferenceApplied', COALESCE(v_apply_preference, false))
  FROM (VALUES('admin', v_admin), ('reply', v_reply), ('telegram', v_telegram)) AS notification(kind, enabled)
  WHERE enabled;
  SELECT COALESCE(jsonb_agg(jsonb_build_object('id', id, 'kind', kind)), '[]'::jsonb)
    INTO v_notification_ids FROM public.email_notifications WHERE message_id = v_message_id;
  RETURN jsonb_build_object('status', 'saved', 'contact_id', v_contact.id, 'request_id', v_request_id,
    'message_id', v_message_id, 'preference_applied', COALESCE(v_apply_preference, false),
    'send_reply', COALESCE(v_reply, false), 'notify_admin', COALESCE(v_admin, false),
    'notify_telegram', v_telegram, 'notifications', v_notification_ids,
    'data', p_payload || jsonb_build_object('contact', v_contact_data));
END
$function$;

REVOKE ALL ON FUNCTION public.persist_known_contact_email(jsonb) FROM PUBLIC;

-- Existing application role owns the base tables. Permit the new outbox/event
-- tables without broad schema/database grants or changing ownership.
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'multisoluciones_web_app') THEN
    GRANT SELECT, INSERT, UPDATE ON public.contact_preference_events,
      public.email_notifications TO multisoluciones_web_app;
    GRANT USAGE, SELECT ON SEQUENCE public.contact_preference_events_id_seq,
      public.email_notifications_id_seq TO multisoluciones_web_app;
    GRANT EXECUTE ON FUNCTION public.persist_known_contact_email(jsonb) TO multisoluciones_web_app;
  END IF;
END
$migration$;
