import Image from 'next/image';
import { getTranslations } from 'next-intl/server';

type Showcase = { id: string; category: string; name: string; headline: string; description: string; action: string; services: string[]; image: string; alt: string; tone: string; button: string };

const showcases: Showcase[] = [
  { id: 'cleaning', category: 'Cleaning services', name: 'Brightly Home', headline: 'A cleaner space, right on schedule.', description: 'Thoughtful care for homes, offices and fresh starts.', action: 'Request a quote', services: ['Home care', 'Office care', 'Deep cleaning'], image: '/industry-showcase/cleaning-services.png', alt: 'Bright living room with cleaning supplies', tone: 'from-sky-100 via-white to-emerald-50 dark:from-sky-950/45 dark:via-surface dark:to-emerald-950/35', button: 'bg-sky-700 text-white dark:bg-sky-300 dark:text-slate-950' },
  { id: 'construction', category: 'Construction & remodeling', name: 'Craft & Corner', headline: 'Built around the way you live.', description: 'Renovation work with a considered eye for every finish.', action: 'Plan your project', services: ['Remodeling', 'Custom builds', 'Home repairs'], image: '/industry-showcase/construction-remodeling.png', alt: 'Finished warm-toned home renovation with a workbench', tone: 'from-amber-100 via-stone-50 to-orange-100 dark:from-amber-950/35 dark:via-stone-950/40 dark:to-orange-950/25', button: 'bg-stone-800 text-white dark:bg-stone-100 dark:text-stone-950' },
  { id: 'landscaping', category: 'Landscaping & irrigation', name: 'Root & Water', headline: 'Outdoor spaces made to thrive.', description: 'Garden care and irrigation planned for every season.', action: 'Explore garden care', services: ['Garden design', 'Irrigation', 'Seasonal care'], image: '/industry-showcase/landscaping-irrigation.png', alt: 'Well-kept garden with discreet drip irrigation', tone: 'from-lime-100 via-white to-emerald-100 dark:from-lime-950/30 dark:via-surface dark:to-emerald-950/35', button: 'bg-emerald-800 text-white dark:bg-emerald-300 dark:text-emerald-950' },
  { id: 'electrical', category: 'Electrical services', name: 'Northline Electric', headline: 'Power, planned with precision.', description: 'Clear solutions for the systems that keep your space moving.', action: 'Talk to an expert', services: ['Installations', 'Upgrades', 'Diagnostics'], image: '/industry-showcase/electrical-services.png', alt: 'Professional inspecting an electrical panel', tone: 'from-slate-950 via-slate-900 to-blue-950 text-white', button: 'bg-blue-400 text-slate-950' },
  { id: 'plumbing', category: 'Plumbing services', name: 'Flowwell Plumbing', headline: 'The details behind a home that flows.', description: 'Reliable repairs and clean installations, from start to finish.', action: 'Schedule a visit', services: ['Repairs', 'Installations', 'Maintenance'], image: '/industry-showcase/plumbing-services.png', alt: 'Clean plumbing installation beneath a kitchen sink', tone: 'from-cyan-100 via-white to-blue-50 dark:from-cyan-950/35 dark:via-surface dark:to-blue-950/30', button: 'bg-cyan-800 text-white dark:bg-cyan-300 dark:text-cyan-950' },
  { id: 'auto', category: 'Mobile auto service', name: 'Roadside Method', headline: 'Service that meets you where you are.', description: 'Straightforward diagnostics and repairs for everyday driving.', action: 'Book mobile service', services: ['Diagnostics', 'Maintenance', 'On-site repair'], image: '/industry-showcase/mobile-auto-service.png', alt: 'Mechanic working beside a mobile service van', tone: 'from-zinc-950 via-zinc-900 to-amber-950 text-white', button: 'bg-amber-300 text-zinc-950' },
  { id: 'pool', category: 'Pool cleaning & maintenance', name: 'Clearwater Care', headline: 'Clear water. Simple care.', description: 'A calmer way to keep every swim ready for the weekend.', action: 'Find your care plan', services: ['Weekly care', 'Equipment repair', 'Seasonal service'], image: '/industry-showcase/pool-maintenance.png', alt: 'Clear residential pool with a skimmer', tone: 'from-cyan-100 via-sky-50 to-amber-50 dark:from-cyan-950/35 dark:via-sky-950/30 dark:to-amber-950/20', button: 'bg-sky-800 text-white dark:bg-sky-300 dark:text-sky-950' }
];

export async function IndustryShowcase() {
  const t = await getTranslations('HomePage');
  return <section aria-labelledby="industry-showcase-heading">
    <div className="grid gap-5 border-b border-border pb-9 md:grid-cols-2 md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-brand-strong">{t('industryEyebrow')}</p><h2 className="mt-3 max-w-2xl text-3xl font-semibold leading-tight tracking-tight text-foreground sm:text-4xl" id="industry-showcase-heading">{t('industryTitle')}</h2></div><div className="max-w-xl md:justify-self-end"><p className="text-base leading-7 text-muted">{t('industryIntro')}</p><p className="mt-3 border-l-2 border-brand/45 pl-3 text-sm leading-6 text-muted">{t('industryNote')}</p></div></div>
    <div className="mt-8 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{showcases.map((item) => <article className={`overflow-hidden rounded-3xl border border-border bg-gradient-to-br shadow-sm ${item.tone}`} key={item.id}><div className="flex items-center justify-between px-5 pb-3 pt-5 text-[0.65rem] font-bold uppercase tracking-[0.16em] opacity-75"><span>{item.name}</span><span aria-hidden="true">↗</span></div><div className="relative mx-3 aspect-[16/9] overflow-hidden rounded-2xl"><Image alt={item.alt} className="object-cover" fill sizes="(max-width: 639px) calc(100vw - 2.5rem), (max-width: 1279px) calc(50vw - 2.5rem), 18rem" src={item.image} /></div><div className="p-5"><p className="text-[0.65rem] font-bold uppercase tracking-[0.16em] opacity-65">{item.category}</p><h3 className="mt-3 text-xl font-semibold leading-tight tracking-tight">{item.headline}</h3><p className="mt-3 text-sm leading-6 opacity-75">{item.description}</p><ul className="mt-5 flex flex-wrap gap-2" aria-label={`${item.name} services`}>{item.services.map((service) => <li className="rounded-full border border-current/15 px-2.5 py-1 text-[0.65rem] font-semibold leading-4" key={service}>{service}</li>)}</ul><span className={`mt-6 inline-flex rounded-full px-3.5 py-2 text-xs font-bold ${item.button}`}>{item.action}</span></div></article>)}</div>
  </section>;
}
